App\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    firstName:
      type: string
      column: first_name
    lastName:
      type: string
      column: last_name
    gender:
      type: smallint
    namePrefix:
      type: string
      column: name_prefix